### ISSUE TITLE
I can't launch swayvnc-firefox on of firefox browser though it works on remmina and rdp but only one one port.

### ISSUE THREAD

**Issue by RajaMuneerBaigal** [bbusse/swayvnc-firefox#19]
I have used your docker file to build a  docker image and used your run commands to run it. but the port 5000 and port 7023 don't show anything both on remmina and in firefox browser. port 5900 works but in firefox browser it shows some sort of error. I am attaching the screenshot so you can see. I wanna know can we run this swayvnc in a browser or not. 
![image](https://user-images.githubusercontent.com/105891199/197407178-575c7954-5f5c-49a7-bc73-02127c612d76.png)

**Comment by RajaMuneerBaigal** [comment]
Also, I wanna know in your swayvnc image you have configured wayvnc to run on 5910. how can we expose that port to novnc so it can run inside any browser?

**Comment by bbusse** [comment]
Browsers typically don't talk VNC, you need a VNC client like Remmina, the one you used to get input/output (or, well novnc)

You can tell novnc what port to connect to with 'novnc --vnc localhost:5910 '

**Comment by RajaMuneerBaigal** [comment]
then what is the difference between your swayvnc and swayvnc-firefox repository?

**Comment by bbusse** [comment]
Firefox

**Comment by RajaMuneerBaigal** [comment]
I wanna know if you could help me. Can we use your swavnc timage on cloudflare to display vnc in a browser ?

**Comment by bbusse** [comment]
I am not too familiar with Cloudflare's services. If it can run containers, then you can run swayvnc-firefox. Other than than I am not entirely sure what you want to achieve. With swayvnc-firefox as is, you need a VNC-client to get a connection. If you want to use a browser you additionally need something like noVNC. Which then would mean you use a browser to view a remote browser, if that is what you want
